import {
  Wind,
  Thermometer,
  Heater,
  Waves,
  Bath,
  Dumbbell,
  Gamepad2,
  Clapperboard,
  Goal,
  Tv,
  Wifi,
  BedDouble,
  Award,
  Mountain,
  ThermometerSun,
} from "lucide-react";

export const allAmenities = [
  {
    id: "casa_sobre_barranco",
    name: "Casa Sobre barranco",
    icon: Mountain,
    category: "Vistas y Ubicación",
  },
  {
    id: "aire_acondicionado_full",
    name: "Aire acondicionado en todos los ambientes",
    icon: Wind,
    category: "Calefacción y refrigeración",
  },
  {
    id: "climatizador_piscina_externa",
    name: "Climatizador de piscina externa",
    icon: ThermometerSun,
    category: "Bienestar y Relax",
  },
  {
    id: "piscina_interna_climatizada",
    name: "Piscina Interna climatizada",
    icon: Waves,
    category: "Bienestar y Relax",
  },
  {
    id: "sala_juegos",
    name: "Sala de Juegos",
    icon: Gamepad2,
    category: "Entretenimiento",
  },
  {
    id: "minicine_4k",
    name: "Minicine 4K",
    icon: Clapperboard,
    category: "Entretenimiento",
  },
  {
    id: "sommiers_king_size",
    name: "Sommiers King Size",
    icon: BedDouble,
    category: "Dormitorio y Baño",
  },
  {
    id: "hidromasaje",
    name: "Hidromasaje",
    icon: Bath,
    category: "Bienestar y Relax",
  },
  {
    id: "sauna",
    name: "Sauna",
    icon: Heater,
    category: "Bienestar y Relax",
  },
  {
    id: "gimnasio_cubierto",
    name: "Gimnasio cubierto",
    icon: Dumbbell,
    category: "Bienestar y Relax",
  },
  {
    id: "instalacion_deportiva",
    name: "Instalación deportiva",
    icon: Goal,
    category: "Entretenimiento",
  },
  {
    id: "starlink_250",
    name: "Star Link 250",
    icon: Wifi,
    category: "Internet y Oficina",
  },
  {
    id: "starlink_100",
    name: "Star Link 100",
    icon: Wifi,
    category: "Internet y Oficina",
  },
  {
    id: "tv_full_hd_premium",
    name: "TV Full HD Pack premium",
    icon: Tv,
    category: "Entretenimiento",
  },
  {
    id: "piscina_privada",
    name: "Piscina privada",
    icon: Waves,
    category: "Bienestar y Relax",
  },
  {
    id: "calefaccion_central",
    name: "Calefacción central",
    icon: Thermometer,
    category: "Calefacción y refrigeración",
  },
  {
    id: "toalleros_calefaccionados",
    name: "Toalleros calefaccionados",
    icon: Heater,
    category: "Calefacción y refrigeración",
  },
  {
    id: "calidad_constructiva",
    name: "Calidad constructiva",
    icon: Award,
    category: "Características del Inmueble",
  },
];
